// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fsi_fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Links struct {
	_tab flatbuffers.Table
}

func GetRootAsLinks(buf []byte, offset flatbuffers.UOffsetT) *Links {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Links{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Links) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Links) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Links) List(obj *Link, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Links) ListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func LinksStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LinksAddList(builder *flatbuffers.Builder, list flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(list), 0)
}
func LinksStartListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func LinksEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
