// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fsi_fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Link struct {
	_tab flatbuffers.Table
}

func GetRootAsLink(buf []byte, offset flatbuffers.UOffsetT) *Link {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Link{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Link) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Link) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Link) Ref() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Link) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LinkStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LinkAddRef(builder *flatbuffers.Builder, ref flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ref), 0)
}
func LinkAddPath(builder *flatbuffers.Builder, path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(path), 0)
}
func LinkEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
