// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package logfb

import "strconv"

type OpType int8

const (
	OpTypeUnknown OpType = 0
	OpTypeInit    OpType = 1
	OpTypeAmend   OpType = 2
	OpTypeRemove  OpType = 3
)

var EnumNamesOpType = map[OpType]string{
	OpTypeUnknown: "Unknown",
	OpTypeInit:    "Init",
	OpTypeAmend:   "Amend",
	OpTypeRemove:  "Remove",
}

var EnumValuesOpType = map[string]OpType{
	"Unknown": OpTypeUnknown,
	"Init":    OpTypeInit,
	"Amend":   OpTypeAmend,
	"Remove":  OpTypeRemove,
}

func (v OpType) String() string {
	if s, ok := EnumNamesOpType[v]; ok {
		return s
	}
	return "OpType(" + strconv.FormatInt(int64(v), 10) + ")"
}
