// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cron_fbs

type JobType = int8

const (
	JobTypeunknown JobType = 0
	JobTypedataset JobType = 1
	JobTypeshell   JobType = 2
)

var EnumNamesJobType = map[JobType]string{
	JobTypeunknown: "unknown",
	JobTypedataset: "dataset",
	JobTypeshell:   "shell",
}
