// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cron_fbs

type Options = byte

const (
	OptionsNONE               Options = 0
	OptionsDatasetOptions     Options = 1
	OptionsShellScriptOptions Options = 2
)

var EnumNamesOptions = map[Options]string{
	OptionsNONE:               "NONE",
	OptionsDatasetOptions:     "DatasetOptions",
	OptionsShellScriptOptions: "ShellScriptOptions",
}
