// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cron_fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StringMapVal struct {
	_tab flatbuffers.Table
}

func GetRootAsStringMapVal(buf []byte, offset flatbuffers.UOffsetT) *StringMapVal {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StringMapVal{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StringMapVal) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StringMapVal) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StringMapVal) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StringMapVal) Val() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StringMapValStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StringMapValAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func StringMapValAddVal(builder *flatbuffers.Builder, val flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(val), 0)
}
func StringMapValEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
