// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package log_fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Logs struct {
	_tab flatbuffers.Table
}

func GetRootAsLogs(buf []byte, offset flatbuffers.UOffsetT) *Logs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Logs{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Logs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Logs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Logs) List(obj *Log, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Logs) ListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func LogsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LogsAddList(builder *flatbuffers.Builder, list flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(list), 0)
}
func LogsStartListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func LogsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
