// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package log_fbs

type LogType = int8
const (
	LogTypemerge LogType = 0
	LogTypeignore LogType = 1
	LogTypeflag LogType = 2
	LogTypejoin LogType = 3
	LogTypeleave LogType = 4
	LogTypeacl_version LogType = 5
	LogTypedataset_version LogType = 6
	LogTypesuggestion LogType = 7
)

var EnumNamesLogType = map[LogType]string{
	LogTypemerge:"merge",
	LogTypeignore:"ignore",
	LogTypeflag:"flag",
	LogTypejoin:"join",
	LogTypeleave:"leave",
	LogTypeacl_version:"acl_version",
	LogTypedataset_version:"dataset_version",
	LogTypesuggestion:"suggestion",
}

