openapi: 3.0.0
info:
  title: Qri API
  description: Qri API used to communicate with a Qri node.
  version: {{ .QriVersion }}
tags:
{{- range .MethodSets }}
{{- if gt .MethodCount 0}}
- name: {{ .Name }}
  description: "{{ .Doc }}"
{{ end -}}
{{ end -}}
paths:
{{- range .LibMethods }}
{{- if .Endpoint }}
  '{{ .Endpoint }}':
    {{ .HTTPVerb }}:
{{ if .Doc }}      description: {{ .Doc }}{{end}}
      operationId: '{{ .MethodSet }}.{{ .MethodName }}'
      tags:
      - {{ .MethodSet }}
      {{- if eq .HTTPVerb "get" }}
      {{- if eq .Params.Name "pathParams" }}
{{ if .Params.Fields }}      parameters: {{end}}
{{- range .Params.Fields }}
{{- if not .Hidden }}
      - name: '{{ .Name }}'
        in: path
        required: true
        schema:
          type: string
{{ end -}}
{{ end -}}
      {{ end }}
      {{ end -}}
      {{- if eq .HTTPVerb "post" }}
      {{- if ne .Params.Name "" }}
      {{- if not .Params.IsBinary }}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/{{ .Params.Name }}'
      {{ end }}
      {{- if .Params.IsBinary }}
      requestBody:
        required: true
        content:
          {{ .Params.Name }}:
            schema:
              type: string
              format: binary
      {{ end }}
      {{ end -}}
      {{ end }}
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/APIResponse'
                  - properties:
                      data:
{{ if not .Response.IsArray }}
                        allOf:
                          - $ref: '#/components/schemas/{{ .Response.Type }}'
{{ end }}
{{ if .Response.IsArray }}
                        type: array
                        items:
                          allOf:
                            - $ref: '#/components/schemas/{{ .Response.Type }}'
{{ end}}
{{ if .Paginated }}
                      pagination:
                        allOf:
                          - $ref: '#/components/schemas/Pagination'
{{ end }}
          description: OK
        '400':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/APIResponse'
                  - properties:
                      meta:
                        allOf:
                          - $ref: '#/components/schemas/APIMetaError'
          description: Bad request
        '500':
          content:
            application/json:
              schema:
                type: string
                nullable: true
          description: Server error
        default:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/APIResponse'
                  - properties:
                      meta:
                        allOf:
                          - $ref: '#/components/schemas/APIMetaError'
          description: Error
{{- end -}}
{{- end }}

components:
  schemas:
{{- range .Types }}
    {{ .Name }}:
      type: object
{{ if .Fields }}      properties: {{end}}
        {{- range .Fields }}
        {{ if not .Hidden }}
        {{ .Name }}:
{{ if .TypeIsCommon }}          type: {{ .Type }}{{ end }}
{{ if not .TypeIsCommon }}          type: object{{ end }}
{{ if ne .Doc "" }}          description: "{{ .Doc }}"{{ end }}
{{ if ne .Example "" }}          example: "{{ .Example }}"{{ end }}
{{- end }}
{{- end }}
{{- end }}
### Response Schemas
## Base
    APIResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
          nullable: true
    StatusOK:
      type: object
    String:
      type: string
    Nil:
      type: object
      nullable: true
    NotDefined:
      type: object
      nullable: true
    Pagination:
      type: object
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        resultCount:
          type: integer
        nextUrl:
          type: string
        prevUrl:
          type: string
    RawResponse:
      # supports all string formats: string, binary, byte
      type: string
## Qri
    Dataset:
      type: object 
    VersionInfo:
      type: object
    StatusItem:
      type: object
    Profile:
      type: object
    Ref:
      type: object
    DAGManifest:
      type: object
    DAGInfo:
      type: object
    ChangeReport:
      type: object
    MappedArraysOfVersionInfo:
      type: object
      additionalProperties: true
## Error
    APIMetaError:
      type: object
      properties:
        code:
          type: integer
        error:
          type: string